import "dotenv/config";
import { PrismaClient } from "@prisma/client";
const p = new PrismaClient();

// Estos 26 códigos de Proceso los usa la tabla Clase pero no existían en el catálogo
// Procesos del Excel original (probable numeración paralela legacy de la familia "P").
// Se insertan como placeholder para no romper la relación; hay que completar su
// descripción real desde Catálogos → Procesos.
const PROCESOS_FALTANTES = [1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 14, 15, 17, 18, 19, 27, 29, 35, 44, 82, 90, 92, 93, 94, 97, 98];

const CLASES = [
  { Clase: "C20", Familia: "C", Proceso: 20, Descripcion: "CULTIVO CABEZA ENTERO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C23", Familia: "C", Proceso: 23, Descripcion: "CULTIVO CABEZA ENTERO 100% MUDADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C67", Familia: "C", Proceso: 67, Descripcion: "CULTIVO CABEZA ENTERO BF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C69", Familia: "C", Proceso: 69, Descripcion: "CULTIVO CABEZA ENTERO COCINADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C26", Familia: "C", Proceso: 26, Descripcion: "CULTIVO CABEZA ENTERO IQF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C24", Familia: "C", Proceso: 24, Descripcion: "CULTIVO CABEZA ENTERO SIFON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C21", Familia: "C", Proceso: 21, Descripcion: "CULTIVO CABEZA ENTERO-2", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C27", Familia: "C", Proceso: 27, Descripcion: "CULTIVO CABEZA ENTERO-2 IQF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C22", Familia: "C", Proceso: 22, Descripcion: "CULTIVO CABEZA ENTERO-3", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C25", Familia: "C", Proceso: 25, Descripcion: "CULTIVO CABEZA ENTERO-R", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C10", Familia: "C", Proceso: 10, Descripcion: "CULTIVO CABEZA GRANEL", TipoClase: "PRODUCTO FINAL" },
  { Clase: "C66", Familia: "C", Proceso: 66, Descripcion: "CULTIVO CABEZA PINCHOS BF ENTERO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D71", Familia: "D", Proceso: 71, Descripcion: "CULTIVO COLA COCINADO EZ-PEEL", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D30", Familia: "D", Proceso: 30, Descripcion: "CULTIVO COLA COLA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D34", Familia: "D", Proceso: 34, Descripcion: "CULTIVO COLA COLA DEVENADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D35", Familia: "D", Proceso: 35, Descripcion: "CULTIVO COLA COLA SIFON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D31", Familia: "D", Proceso: 31, Descripcion: "CULTIVO COLA COLA-B", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D32", Familia: "D", Proceso: 32, Descripcion: "CULTIVO COLA COLA-C", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D33", Familia: "D", Proceso: 33, Descripcion: "CULTIVO COLA COLA-R", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D16", Familia: "D", Proceso: 16, Descripcion: "CULTIVO COLA DESCABEZADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D10", Familia: "D", Proceso: 10, Descripcion: "CULTIVO COLA GRANEL", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D95", Familia: "D", Proceso: 95, Descripcion: "CULTIVO COLA SP-CASCARA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "D96", Familia: "D", Proceso: 96, Descripcion: "CULTIVO COLA SP-CASCARA Y CABEZA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E61", Familia: "E", Proceso: 61, Descripcion: "CULTIVO PELADO BUTTER ROUND PyD T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E59", Familia: "E", Proceso: 59, Descripcion: "CULTIVO PELADO 3/4 T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E58", Familia: "E", Proceso: 58, Descripcion: "CULTIVO PELADO 3/4 T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E60", Familia: "E", Proceso: 60, Descripcion: "CULTIVO PELADO 3/4 T-ON CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E54", Familia: "E", Proceso: 54, Descripcion: "CULTIVO PELADO BF T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E55", Familia: "E", Proceso: 55, Descripcion: "CULTIVO PELADO BF T-OFF ALINEADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E53", Familia: "E", Proceso: 53, Descripcion: "CULTIVO PELADO BF T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E70", Familia: "E", Proceso: 70, Descripcion: "CULTIVO PELADO COCINADO COLA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E73", Familia: "E", Proceso: 73, Descripcion: "CULTIVO PELADO COCINADO P&D T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E74", Familia: "E", Proceso: 74, Descripcion: "CULTIVO PELADO COCINADO P&D T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E72", Familia: "E", Proceso: 72, Descripcion: "CULTIVO PELADO COCINADO P&D T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E76", Familia: "E", Proceso: 76, Descripcion: "CULTIVO PELADO COCINADO PPV T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E77", Familia: "E", Proceso: 77, Descripcion: "CULTIVO PELADO COCINADO PPV T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E75", Familia: "E", Proceso: 75, Descripcion: "CULTIVO PELADO COCINADO PPV T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E79", Familia: "E", Proceso: 79, Descripcion: "CULTIVO PELADO COCINADO PUD T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E80", Familia: "E", Proceso: 80, Descripcion: "CULTIVO PELADO COCINADO PUD T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E78", Familia: "E", Proceso: 78, Descripcion: "CULTIVO PELADO COCINADO PUD T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E82", Familia: "E", Proceso: 82, Descripcion: "CULTIVO PELADO EMPANIZADO BF T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E89", Familia: "E", Proceso: 89, Descripcion: "CULTIVO PELADO EMPANIZADO BF T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E84", Familia: "E", Proceso: 84, Descripcion: "CULTIVO PELADO EMPANIZADO P&D T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E83", Familia: "E", Proceso: 83, Descripcion: "CULTIVO PELADO EMPANIZADO P&D T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E98", Familia: "E", Proceso: 98, Descripcion: "CULTIVO PELADO EMPANIZADO POPCORN P&D T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E86", Familia: "E", Proceso: 86, Descripcion: "CULTIVO PELADO EMPANIZADO PPV T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E85", Familia: "E", Proceso: 85, Descripcion: "CULTIVO PELADO EMPANIZADO PPV T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E88", Familia: "E", Proceso: 88, Descripcion: "CULTIVO PELADO EMPANIZADO PUD T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E87", Familia: "E", Proceso: 87, Descripcion: "CULTIVO PELADO EMPANIZADO PUD T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E96", Familia: "E", Proceso: 96, Descripcion: "CULTIVO PELADO EMPANIZADO Q/CHEDDAR BF T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E93", Familia: "E", Proceso: 93, Descripcion: "CULTIVO PELADO EMPANIZADO Q/CHILTEPE BF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E95", Familia: "E", Proceso: 95, Descripcion: "T-ON CULTIVO PELADO EMPANIZADO Q/COBANERO BF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E94", Familia: "E", Proceso: 94, Descripcion: "T-ON CULTIVO PELADO EMPANIZADO Q/JALAPEÑO BF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E10", Familia: "E", Proceso: 10, Descripcion: "T-ON CULTIVO PELADO GRANEL", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E41", Familia: "E", Proceso: 41, Descripcion: "CULTIVO PELADO P&D T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E44", Familia: "E", Proceso: 44, Descripcion: "CULTIVO PELADO P&D T-OFF BROKEN", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E42", Familia: "E", Proceso: 42, Descripcion: "CULTIVO PELADO P&D T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E43", Familia: "E", Proceso: 43, Descripcion: "CULTIVO PELADO P&D T-OFF R", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E92", Familia: "E", Proceso: 92, Descripcion: "CULTIVO PELADO P&D T-OFF R SIFON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E40", Familia: "E", Proceso: 40, Descripcion: "CULTIVO PELADO P&D T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E90", Familia: "E", Proceso: 90, Descripcion: "CULTIVO PELADO P&D T-ON R", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E65", Familia: "E", Proceso: 65, Descripcion: "CULTIVO PELADO PINCHOS BF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E64", Familia: "E", Proceso: 64, Descripcion: "CULTIVO PELADO PINCHOS T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E63", Familia: "E", Proceso: 63, Descripcion: "CULTIVO PELADO PINCHOS T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E46", Familia: "E", Proceso: 46, Descripcion: "CULTIVO PELADO PPV T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E47", Familia: "E", Proceso: 47, Descripcion: "CULTIVO PELADO PPV T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E91", Familia: "E", Proceso: 91, Descripcion: "CULTIVO PELADO PPV T-OFF R", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E45", Familia: "E", Proceso: 45, Descripcion: "CULTIVO PELADO PPV T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E97", Familia: "E", Proceso: 97, Descripcion: "CULTIVO PELADO PPV T-ON R", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E50", Familia: "E", Proceso: 50, Descripcion: "CULTIVO PELADO PUD T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E51", Familia: "E", Proceso: 51, Descripcion: "CULTIVO PELADO PUD T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "E49", Familia: "E", Proceso: 49, Descripcion: "CULTIVO PELADO PUD T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F59", Familia: "F", Proceso: 59, Descripcion: "CULTIVO CERTIFICADO 3/4 T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F58", Familia: "F", Proceso: 58, Descripcion: "CULTIVO CERTIFICADO 3/4 T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F60", Familia: "F", Proceso: 60, Descripcion: "CULTIVO CERTIFICADO 3/4 T-ON CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F54", Familia: "F", Proceso: 54, Descripcion: "CULTIVO CERTIFICADO BF T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F55", Familia: "F", Proceso: 55, Descripcion: "CULTIVO CERTIFICADO BF T-OFF ALINEADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F53", Familia: "F", Proceso: 53, Descripcion: "CULTIVO CERTIFICADO BF T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F71", Familia: "F", Proceso: 71, Descripcion: "CULTIVO CERTIFICADO COCINADO EZ-PEEL", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F73", Familia: "F", Proceso: 73, Descripcion: "CULTIVO CERTIFICADO COCINADO P&D T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F74", Familia: "F", Proceso: 74, Descripcion: "CULTIVO CERTIFICADO COCINADO P&D T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F72", Familia: "F", Proceso: 72, Descripcion: "CULTIVO CERTIFICADO COCINADO P&D T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F76", Familia: "F", Proceso: 76, Descripcion: "CULTIVO CERTIFICADO COCINADO PPV T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F77", Familia: "F", Proceso: 77, Descripcion: "CULTIVO CERTIFICADO COCINADO PPV T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F75", Familia: "F", Proceso: 75, Descripcion: "CULTIVO CERTIFICADO COCINADO PPV T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F79", Familia: "F", Proceso: 79, Descripcion: "CULTIVO CERTIFICADO COCINADO PUD T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F80", Familia: "F", Proceso: 80, Descripcion: "CULTIVO CERTIFICADO COCINADO PUD T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F78", Familia: "F", Proceso: 78, Descripcion: "CULTIVO CERTIFICADO COCINADO PUD T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F30", Familia: "F", Proceso: 30, Descripcion: "CULTIVO CERTIFICADO COLA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F31", Familia: "F", Proceso: 31, Descripcion: "CULTIVO CERTIFICADO COLA-2", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F32", Familia: "F", Proceso: 32, Descripcion: "CULTIVO CERTIFICADO COLA-3", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F16", Familia: "F", Proceso: 16, Descripcion: "CULTIVO CERTIFICADO DESCABEZADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F84", Familia: "F", Proceso: 84, Descripcion: "CULTIVO CERTIFICADO EMPANIZADO P&D T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F83", Familia: "F", Proceso: 83, Descripcion: "CULTIVO CERTIFICADO EMPANIZADO P&D T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F86", Familia: "F", Proceso: 86, Descripcion: "CULTIVO CERTIFICADO EMPANIZADO PPV T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F85", Familia: "F", Proceso: 85, Descripcion: "CULTIVO CERTIFICADO EMPANIZADO PPV T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F88", Familia: "F", Proceso: 88, Descripcion: "CULTIVO CERTIFICADO EMPANIZADO PUD T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F87", Familia: "F", Proceso: 87, Descripcion: "CULTIVO CERTIFICADO EMPANIZADO PUD T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F20", Familia: "F", Proceso: 20, Descripcion: "CULTIVO CERTIFICADO ENTERO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F23", Familia: "F", Proceso: 23, Descripcion: "CULTIVO CERTIFICADO ENTERO 100% MUDADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F21", Familia: "F", Proceso: 21, Descripcion: "CULTIVO CERTIFICADO ENTERO-B", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F22", Familia: "F", Proceso: 22, Descripcion: "CULTIVO CERTIFICADO ENTERO-C", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F10", Familia: "F", Proceso: 10, Descripcion: "CULTIVO CERTIFICADO GRANEL", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F41", Familia: "F", Proceso: 41, Descripcion: "CULTIVO CERTIFICADO P&D T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F42", Familia: "F", Proceso: 42, Descripcion: "CULTIVO CERTIFICADO P&D T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F40", Familia: "F", Proceso: 40, Descripcion: "CULTIVO CERTIFICADO P&D T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F65", Familia: "F", Proceso: 65, Descripcion: "CULTIVO CERTIFICADO PINCHOS BF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F66", Familia: "F", Proceso: 66, Descripcion: "CULTIVO CERTIFICADO PINCHOS BF ENTERO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F64", Familia: "F", Proceso: 64, Descripcion: "CULTIVO CERTIFICADO PINCHOS T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F63", Familia: "F", Proceso: 63, Descripcion: "CULTIVO CERTIFICADO PINCHOS T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F46", Familia: "F", Proceso: 46, Descripcion: "CULTIVO CERTIFICADO PPV T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F47", Familia: "F", Proceso: 47, Descripcion: "CULTIVO CERTIFICADO PPV T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F45", Familia: "F", Proceso: 45, Descripcion: "CULTIVO CERTIFICADO PPV T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F50", Familia: "F", Proceso: 50, Descripcion: "CULTIVO CERTIFICADO PUD T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F51", Familia: "F", Proceso: 51, Descripcion: "CULTIVO CERTIFICADO PUD T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F49", Familia: "F", Proceso: 49, Descripcion: "CULTIVO CERTIFICADO PUD T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F95", Familia: "F", Proceso: 95, Descripcion: "CULTIVO CERTIFICADO SP-CASCARA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "F96", Familia: "F", Proceso: 96, Descripcion: "CULTIVO CERTIFICADO SP-CASCARA Y CABEZA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H30", Familia: "H", Proceso: 30, Descripcion: "CULTIVO RETENIDO COLA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H31", Familia: "H", Proceso: 31, Descripcion: "CULTIVO RETENIDO COLA-2", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H32", Familia: "H", Proceso: 32, Descripcion: "CULTIVO RETENIDO COLA-3", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H33", Familia: "H", Proceso: 33, Descripcion: "CULTIVO RETENIDO COLA-R", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H16", Familia: "H", Proceso: 16, Descripcion: "CULTIVO RETENIDO DESCABEZADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H20", Familia: "H", Proceso: 20, Descripcion: "CULTIVO RETENIDO ENTERO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H23", Familia: "H", Proceso: 23, Descripcion: "CULTIVO RETENIDO ENTERO 100% MUDADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H21", Familia: "H", Proceso: 21, Descripcion: "CULTIVO RETENIDO ENTERO-2", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H22", Familia: "H", Proceso: 22, Descripcion: "CULTIVO RETENIDO ENTERO-3", TipoClase: "PRODUCTO FINAL" },
  { Clase: "H10", Familia: "H", Proceso: 10, Descripcion: "CULTIVO RETENIDO GRANEL", TipoClase: "PRODUCTO FINAL" },
  { Clase: "L20", Familia: "L", Proceso: 20, Descripcion: "GAMBON CABEZA GAMBON CABEZA ENTERO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "L23", Familia: "L", Proceso: 23, Descripcion: "GAMBON CABEZA ENTERO 100% MUDADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "L21", Familia: "L", Proceso: 21, Descripcion: "GAMBON CABEZA ENTERO-2", TipoClase: "PRODUCTO FINAL" },
  { Clase: "L22", Familia: "L", Proceso: 22, Descripcion: "GAMBON CABEZA ENTERO-3", TipoClase: "PRODUCTO FINAL" },
  { Clase: "M30", Familia: "M", Proceso: 30, Descripcion: "GAMBON COLA COLA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "M31", Familia: "M", Proceso: 31, Descripcion: "GAMBON COLA COLA-2", TipoClase: "PRODUCTO FINAL" },
  { Clase: "M32", Familia: "M", Proceso: 32, Descripcion: "GAMBON COLA COLA-3", TipoClase: "PRODUCTO FINAL" },
  { Clase: "M33", Familia: "M", Proceso: 33, Descripcion: "GAMBON COLA ROTA", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N54", Familia: "N", Proceso: 54, Descripcion: "GAMBON PELADO BF T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N55", Familia: "N", Proceso: 55, Descripcion: "GAMBON PELADO BF T-OFF ALINEADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N53", Familia: "N", Proceso: 53, Descripcion: "GAMBON PELADO BF T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N41", Familia: "N", Proceso: 41, Descripcion: "GAMBON PELADO P&D T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N42", Familia: "N", Proceso: 42, Descripcion: "GAMBON PELADO P&D T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N40", Familia: "N", Proceso: 40, Descripcion: "GAMBON PELADO P&D T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N46", Familia: "N", Proceso: 46, Descripcion: "GAMBON PELADO PPV T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N47", Familia: "N", Proceso: 47, Descripcion: "GAMBON PELADO PPV T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N45", Familia: "N", Proceso: 45, Descripcion: "GAMBON PELADO PPV T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N50", Familia: "N", Proceso: 50, Descripcion: "GAMBON PELADO PUD T-OFF", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N51", Familia: "N", Proceso: 51, Descripcion: "GAMBON PELADO PUD T-OFF CC", TipoClase: "PRODUCTO FINAL" },
  { Clase: "N49", Familia: "N", Proceso: 49, Descripcion: "GAMBON PELADO PUD T-ON", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P01", Familia: "P", Proceso: 1, Descripcion: "CULTIVO CABEZA ENTERO *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P05", Familia: "P", Proceso: 5, Descripcion: "CULTIVO CABEZA ENTERO SIFON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P02", Familia: "P", Proceso: 2, Descripcion: "CULTIVO CABEZA ENTERO-2 *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P03", Familia: "P", Proceso: 3, Descripcion: "CULTIVO CABEZA ENTERO-3 *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P04", Familia: "P", Proceso: 4, Descripcion: "CULTIVO CABEZA GRANEL *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P08", Familia: "P", Proceso: 8, Descripcion: "CULTIVO COLA COLA *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P09", Familia: "P", Proceso: 9, Descripcion: "CULTIVO COLA COLA-2 *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P10", Familia: "P", Proceso: 10, Descripcion: "CULTIVO COLA COLA-3 *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P11", Familia: "P", Proceso: 11, Descripcion: "CULTIVO COLA COLA-R *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P07", Familia: "P", Proceso: 7, Descripcion: "CULTIVO COLA DESCABEZADO *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P06", Familia: "P", Proceso: 6, Descripcion: "CULTIVO COLA GRANEL *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P22", Familia: "P", Proceso: 22, Descripcion: "CULTIVO PELADO * CULTIVO PELADO BF T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P21", Familia: "P", Proceso: 21, Descripcion: "CULTIVO PELADO BF T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P23", Familia: "P", Proceso: 23, Descripcion: "CULTIVO PELADO COCINADO COLA *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P25", Familia: "P", Proceso: 25, Descripcion: "CULTIVO PELADO COCINADO P&D T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P24", Familia: "P", Proceso: 24, Descripcion: "CULTIVO PELADO COCINADO P&D T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P27", Familia: "P", Proceso: 27, Descripcion: "CULTIVO PELADO COCINADO PPV T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P26", Familia: "P", Proceso: 26, Descripcion: "CULTIVO PELADO COCINADO PPV T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P30", Familia: "P", Proceso: 30, Descripcion: "CULTIVO PELADO COCINADO PUD T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P29", Familia: "P", Proceso: 29, Descripcion: "CULTIVO PELADO COCINADO PUD T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P32", Familia: "P", Proceso: 32, Descripcion: "CULTIVO PELADO EMPANIZADO P&D T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P31", Familia: "P", Proceso: 31, Descripcion: "CULTIVO PELADO EMPANIZADO P&D T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P34", Familia: "P", Proceso: 34, Descripcion: "CULTIVO PELADO EMPANIZADO PPV T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P33", Familia: "P", Proceso: 33, Descripcion: "CULTIVO PELADO EMPANIZADO PPV T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P35", Familia: "P", Proceso: 35, Descripcion: "CULTIVO PELADO EMPANIZADO PUD T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P12", Familia: "P", Proceso: 12, Descripcion: "CULTIVO PELADO GRANEL *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P14", Familia: "P", Proceso: 14, Descripcion: "CULTIVO PELADO P&D T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P16", Familia: "P", Proceso: 16, Descripcion: "CULTIVO PELADO P&D T-OFF BROKEN *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P15", Familia: "P", Proceso: 15, Descripcion: "CULTIVO PELADO P&D T-OFF R *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P13", Familia: "P", Proceso: 13, Descripcion: "CULTIVO PELADO P&D T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P18", Familia: "P", Proceso: 18, Descripcion: "CULTIVO PELADO PPV T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P17", Familia: "P", Proceso: 17, Descripcion: "CULTIVO PELADO PPV T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P20", Familia: "P", Proceso: 20, Descripcion: "CULTIVO PELADO PUD T-OFF *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "P19", Familia: "P", Proceso: 19, Descripcion: "CULTIVO PELADO PUD T-ON *", TipoClase: "PRODUCTO FINAL" },
  { Clase: "T03", Familia: "T", Proceso: 3, Descripcion: "CARNE DE ATUN", TipoClase: "PRODUCTO FINAL" },
  { Clase: "T06", Familia: "T", Proceso: 6, Descripcion: "CEVICHERO DORADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "T02", Familia: "T", Proceso: 2, Descripcion: "MEDALLONES DE ATUN", TipoClase: "PRODUCTO FINAL" },
  { Clase: "T07", Familia: "T", Proceso: 7, Descripcion: "PESCADO DORADO", TipoClase: "PRODUCTO FINAL" },
  { Clase: "T01", Familia: "T", Proceso: 1, Descripcion: "PIEZAS DE ATUN", TipoClase: "PRODUCTO FINAL" },
  { Clase: "T05", Familia: "T", Proceso: 5, Descripcion: "PORCIONES DE ATUN", TipoClase: "PRODUCTO FINAL" },
  { Clase: "T08", Familia: "T", Proceso: 8, Descripcion: "PORCIONES DE ATUN B", TipoClase: "PRODUCTO FINAL" },
  { Clase: "T04", Familia: "T", Proceso: 4, Descripcion: "TORO DE ATUN", TipoClase: "PRODUCTO FINAL" },
];

const PRESENTACIONES = [
  { Codigo: "AA", Descripcion: "1/1 kg (1 kg)", Abreviatura: "1 KG", TipoMedida: "Kilos", PesoKG: 1.0, PesoLb: 2.2, CajasXMaster: 1 },
  { Codigo: "AS", Descripcion: "2/10 kg (20 kg)", Abreviatura: "10 KG", TipoMedida: "Kilos", PesoKG: 10.0, PesoLb: 22.05, CajasXMaster: 2 },
  { Codigo: "CJ", Descripcion: "10/3 lb (30 lb)", Abreviatura: "3 LB", TipoMedida: "libras", PesoKG: 1.36, PesoLb: 3.0, CajasXMaster: 10 },
  { Codigo: "EJ", Descripcion: "19/1.18 lb (22..42 lb)", Abreviatura: "1.18 LB", TipoMedida: "libras", PesoKG: 0.54, PesoLb: 1.18, CajasXMaster: 19 },
  { Codigo: "FA", Descripcion: "20/0.5 lb(10lb)", Abreviatura: "0.5 LB", TipoMedida: "libras", PesoKG: 0.23, PesoLb: 0.5, CajasXMaster: 20 },
  { Codigo: "FB", Descripcion: "32/4-6 oz (10lb)", Abreviatura: "4-6 OZ", TipoMedida: "libras", PesoKG: 0.14, PesoLb: 0.31, CajasXMaster: 32 },
  { Codigo: "FG", Descripcion: "40/4 oz (10 lb)", Abreviatura: "4 OZ", TipoMedida: "libras", PesoKG: 0.11, PesoLb: 0.25, CajasXMaster: 40 },
  { Codigo: "FH", Descripcion: "26/6 oz (10 lb)", Abreviatura: "6 OZ", TipoMedida: "libras", PesoKG: 0.17, PesoLb: 0.38, CajasXMaster: 26 },
  { Codigo: "FJ", Descripcion: "20/8 oz (10 lb)", Abreviatura: "8 OZ", TipoMedida: "libras", PesoKG: 0.23, PesoLb: 0.5, CajasXMaster: 20 },
  { Codigo: "FK", Descripcion: "16/10 oz (10 lb)", Abreviatura: "10 OZ", TipoMedida: "libras", PesoKG: 0.28, PesoLb: 0.63, CajasXMaster: 16 },
  { Codigo: "FL", Descripcion: "40/ 8 oz(20 lb)", Abreviatura: "8 OZ", TipoMedida: "libras", PesoKG: 0.23, PesoLb: 0.5, CajasXMaster: 40 },
  { Codigo: "FQ", Descripcion: "1/10 kg (10 kg)", Abreviatura: "10 kg", TipoMedida: "Kilos", PesoKG: 10.0, PesoLb: 22.05, CajasXMaster: 1 },
  { Codigo: "FR", Descripcion: "10/1-3 oz (10 lb)", Abreviatura: "1-3 OZ", TipoMedida: "libras", PesoKG: 0.45, PesoLb: 1.0, CajasXMaster: 10 },
  { Codigo: "GF", Descripcion: "5/4 lb ( 20 lb )", Abreviatura: "4 LB", TipoMedida: "libras", PesoKG: 1.81, PesoLb: 4.0, CajasXMaster: 5 },
  { Codigo: "GM", Descripcion: "3/6 kg (18 kg)", Abreviatura: "6 KG", TipoMedida: "Kilos", PesoKG: 6.0, PesoLb: 13.23, CajasXMaster: 3 },
  { Codigo: "JL", Descripcion: "30/1 lb (30 lb)", Abreviatura: "1 LB", TipoMedida: "libras", PesoKG: 0.45, PesoLb: 1.0, CajasXMaster: 30 },
  { Codigo: "LA", Descripcion: "19/1.05 lb (20 lb)", Abreviatura: "1.05 LB", TipoMedida: "libras", PesoKG: 0.48, PesoLb: 1.05, CajasXMaster: 19 },
  { Codigo: "LS", Descripcion: "24/450 gr (10.89 kg)", Abreviatura: "450 GR", TipoMedida: "Kilos", PesoKG: 0.45, PesoLb: 1.0, CajasXMaster: 24 },
  { Codigo: "LT", Descripcion: "18/1.11 lb ( 20 lb)", Abreviatura: "1.11 LB", TipoMedida: "libras", PesoKG: 0.5, PesoLb: 1.11, CajasXMaster: 18 },
  { Codigo: "MA", Descripcion: "12/450 gr (5.4 kg)", Abreviatura: "450 GR", TipoMedida: "Kilos", PesoKG: 0.45, PesoLb: 0.99, CajasXMaster: 12 },
  { Codigo: "MB", Descripcion: "24/450 gr(10.8 kg)", Abreviatura: "450 GR", TipoMedida: "Kilos", PesoKG: 0.45, PesoLb: 0.99, CajasXMaster: 24 },
  { Codigo: "MD", Descripcion: "16/450 gr (7.2 kg)", Abreviatura: "450 GR", TipoMedida: "Kilos", PesoKG: 0.45, PesoLb: 0.99, CajasXMaster: 16 },
  { Codigo: "MG", Descripcion: "22/450 gr (9.9 kg)", Abreviatura: "450 GR", TipoMedida: "Kilos", PesoKG: 0.45, PesoLb: 0.99, CajasXMaster: 22 },
  { Codigo: "MH", Descripcion: "20/450 gr(9 kg)", Abreviatura: "450 GR", TipoMedida: "Kilos", PesoKG: 0.45, PesoLb: 0.99, CajasXMaster: 20 },
  { Codigo: "MJ", Descripcion: "12/480 gr(5.76kg)", Abreviatura: "480 GR", TipoMedida: "Kilos", PesoKG: 0.48, PesoLb: 1.06, CajasXMaster: 12 },
  { Codigo: "MK", Descripcion: "16/480 gr (7.68 kg)", Abreviatura: "480 GR", TipoMedida: "Kilos", PesoKG: 0.48, PesoLb: 1.06, CajasXMaster: 16 },
  { Codigo: "MM", Descripcion: "22/480 gr (10.56 kg)", Abreviatura: "480 GR", TipoMedida: "Kilos", PesoKG: 0.65, PesoLb: 1.43, CajasXMaster: 22 },
  { Codigo: "MP", Descripcion: "14/650 gr (9.1 kg)", Abreviatura: "650 GR", TipoMedida: "Kilos", PesoKG: 0.65, PesoLb: 1.43, CajasXMaster: 14 },
  { Codigo: "MR", Descripcion: "22/650 gr (14.3 kg)", Abreviatura: "650 GR", TipoMedida: "Kilos", PesoKG: 0.65, PesoLb: 1.43, CajasXMaster: 22 },
  { Codigo: "MS", Descripcion: "12/650 gr (7.7 kg)", Abreviatura: "650 GR", TipoMedida: "Kilos", PesoKG: 0.65, PesoLb: 1.43, CajasXMaster: 12 },
  { Codigo: "MT", Descripcion: "22/680 gr (14.96 kg)", Abreviatura: "680 GR", TipoMedida: "Kilos", PesoKG: 0.68, PesoLb: 1.5, CajasXMaster: 22 },
  { Codigo: "MV", Descripcion: "16/650 gr (10.4 kg)", Abreviatura: "650 GR", TipoMedida: "Kilos", PesoKG: 0.65, PesoLb: 1.43, CajasXMaster: 16 },
  { Codigo: "MY", Descripcion: "20/650 gr (13 kg)", Abreviatura: "650 GR", TipoMedida: "Kilos", PesoKG: 0.65, PesoLb: 1.43, CajasXMaster: 20 },
  { Codigo: "NA", Descripcion: "14/680 gr (9.52 kg)", Abreviatura: "680 GR", TipoMedida: "Kilos", PesoKG: 0.68, PesoLb: 1.5, CajasXMaster: 14 },
  { Codigo: "NB", Descripcion: "19/523 gr (9.9 kg)", Abreviatura: "523 GR", TipoMedida: "Kilos", PesoKG: 0.52, PesoLb: 1.15, CajasXMaster: 19 },
  { Codigo: "NC", Descripcion: "10/ 720 gr (7.2 kg)", Abreviatura: "720 GR", TipoMedida: "Kilos", PesoKG: 0.72, PesoLb: 1.59, CajasXMaster: 10 },
  { Codigo: "NE", Descripcion: "5/2 kg(10kg)", Abreviatura: "2 KG", TipoMedida: "Kilos", PesoKG: 2.0, PesoLb: 4.41, CajasXMaster: 5 },
  { Codigo: "NG", Descripcion: "10/1 lb (10 lb)", Abreviatura: "1 LB", TipoMedida: "libras", PesoKG: 0.45, PesoLb: 1.0, CajasXMaster: 10 },
  { Codigo: "NK", Descripcion: "5/2 lb (10 lb)", Abreviatura: "2 LB", TipoMedida: "libras", PesoKG: 0.91, PesoLb: 2.0, CajasXMaster: 5 },
  { Codigo: "NL", Descripcion: "4/5 lb (20 lb)", Abreviatura: "5 LB", TipoMedida: "libras", PesoKG: 2.27, PesoLb: 5.0, CajasXMaster: 4 },
  { Codigo: "NM", Descripcion: "1/15 lb (15 lb)", Abreviatura: "15 LB", TipoMedida: "libras", PesoKG: 6.8, PesoLb: 15.0, CajasXMaster: 1 },
  { Codigo: "NP", Descripcion: "6/3 lb (18 lb)", Abreviatura: "3 LB", TipoMedida: "libras", PesoKG: 1.36, PesoLb: 3.0, CajasXMaster: 6 },
  { Codigo: "NS", Descripcion: "9/2 lb (18 lb)", Abreviatura: "2 LB", TipoMedida: "libras", PesoKG: 0.91, PesoLb: 2.0, CajasXMaster: 9 },
  { Codigo: "NV", Descripcion: "10/2 lb (20 lb)", Abreviatura: "2 LB", TipoMedida: "libras", PesoKG: 0.91, PesoLb: 2.0, CajasXMaster: 10 },
  { Codigo: "NW", Descripcion: "4/3 Lb(12 lb)", Abreviatura: "3 LB", TipoMedida: "libras", PesoKG: 1.36, PesoLb: 3.0, CajasXMaster: 4 },
  { Codigo: "NY", Descripcion: "20/1 lb (20 lb)", Abreviatura: "1 LB", TipoMedida: "libras", PesoKG: 0.45, PesoLb: 1.0, CajasXMaster: 20 },
  { Codigo: "NZ", Descripcion: "20/340 gr (6.8 kg)", Abreviatura: "340 GR", TipoMedida: "Kilos", PesoKG: 0.34, PesoLb: 0.75, CajasXMaster: 20 },
  { Codigo: "PA", Descripcion: "14/1.5 lb (21 lb)", Abreviatura: "1.5 LB", TipoMedida: "libras", PesoKG: 0.68, PesoLb: 1.5, CajasXMaster: 14 },
  { Codigo: "PD", Descripcion: "6/4 lb (24 lb)", Abreviatura: "4 LB", TipoMedida: "libras", PesoKG: 1.81, PesoLb: 4.0, CajasXMaster: 6 },
  { Codigo: "PG", Descripcion: "6/4.4 lb (26.4 lb)", Abreviatura: "4.4 LB", TipoMedida: "libras", PesoKG: 2.0, PesoLb: 4.4, CajasXMaster: 6 },
  { Codigo: "PK", Descripcion: "14/2 lb (28 lb)", Abreviatura: "2 LB", TipoMedida: "libras", PesoKG: 0.91, PesoLb: 2.0, CajasXMaster: 14 },
  { Codigo: "PM", Descripcion: "1/30 lb (30 lb)", Abreviatura: "30 LB", TipoMedida: "libras", PesoKG: 13.61, PesoLb: 30.0, CajasXMaster: 1 },
  { Codigo: "PP", Descripcion: "10/4 lb (40 lb)", Abreviatura: "4 LB", TipoMedida: "libras", PesoKG: 1.81, PesoLb: 4.0, CajasXMaster: 10 },
  { Codigo: "PQ", Descripcion: "1/20 lb (20 lb)", Abreviatura: "20 LB", TipoMedida: "libras", PesoKG: 9.07, PesoLb: 20.0, CajasXMaster: 1 },
  { Codigo: "PS", Descripcion: "2/20 lb (40 lb)", Abreviatura: "20 LB", TipoMedida: "libras", PesoKG: 9.07, PesoLb: 20.0, CajasXMaster: 2 },
  { Codigo: "PT", Descripcion: "1/25 lb (25lb)", Abreviatura: "25 LB", TipoMedida: "libras", PesoKG: 11.34, PesoLb: 25.0, CajasXMaster: 1 },
  { Codigo: "PV", Descripcion: "1/40 lb (40 lb)", Abreviatura: "40 LB", TipoMedida: "libras", PesoKG: 18.14, PesoLb: 40.0, CajasXMaster: 1 },
  { Codigo: "PY", Descripcion: "10/5 lb (50 lb)", Abreviatura: "5 LB", TipoMedida: "libras", PesoKG: 2.27, PesoLb: 5.0, CajasXMaster: 10 },
  { Codigo: "PZ", Descripcion: "10/4 lb (40 lb)", Abreviatura: "4 LB", TipoMedida: "libras", PesoKG: 1.81, PesoLb: 4.0, CajasXMaster: 10 },
  { Codigo: "QA", Descripcion: "1/50 lb (50 lb)", Abreviatura: "50 LB", TipoMedida: "libras", PesoKG: 22.68, PesoLb: 50.0, CajasXMaster: 1 },
  { Codigo: "QB", Descripcion: "24/1 lb (24 lb)", Abreviatura: "1 LB", TipoMedida: "Kilos", PesoKG: 0.45, PesoLb: 1.0, CajasXMaster: 24 },
  { Codigo: "QC", Descripcion: "10/720 gr(7.2 kg)", Abreviatura: "720 GR", TipoMedida: "Kilos", PesoKG: 0.72, PesoLb: 1.59, CajasXMaster: 10 },
  { Codigo: "QF", Descripcion: "19/500 gr (9.5kg)", Abreviatura: "500 GR", TipoMedida: "Kilos", PesoKG: 0.5, PesoLb: 1.1, CajasXMaster: 19 },
  { Codigo: "QH", Descripcion: "20/375 gr (7.5 kg)", Abreviatura: "375 GR", TipoMedida: "Kilos", PesoKG: 0.38, PesoLb: 0.83, CajasXMaster: 20 },
  { Codigo: "QM", Descripcion: "14/700 gr (9.8kg)", Abreviatura: "700 GR", TipoMedida: "Kilos", PesoKG: 0.7, PesoLb: 1.54, CajasXMaster: 14 },
  { Codigo: "QN", Descripcion: "20/360 gr(7.2 kg)", Abreviatura: "360 GR", TipoMedida: "Kilos", PesoKG: 0.36, PesoLb: 0.79, CajasXMaster: 20 },
  { Codigo: "QP", Descripcion: "1/10 lb (10 lb)", Abreviatura: "10 LB", TipoMedida: "libras", PesoKG: 4.54, PesoLb: 10.0, CajasXMaster: 1 },
  { Codigo: "QR", Descripcion: "25/360 gr (9 kg)", Abreviatura: "360 GR", TipoMedida: "Kilos", PesoKG: 0.36, PesoLb: 0.79, CajasXMaster: 25 },
  { Codigo: "QT", Descripcion: "10/2 kg (20 kg)", Abreviatura: "2 KG", TipoMedida: "Kilos", PesoKG: 2.0, PesoLb: 4.41, CajasXMaster: 10 },
  { Codigo: "QV", Descripcion: "20/420 gr (8.4 kg)", Abreviatura: "420 GR", TipoMedida: "Kilos", PesoKG: 0.42, PesoLb: 0.93, CajasXMaster: 20 },
  { Codigo: "QW", Descripcion: "10/908 gr (9.08 kg)", Abreviatura: "908 GR", TipoMedida: "Kilos", PesoKG: 0.91, PesoLb: 2.0, CajasXMaster: 10 },
  { Codigo: "QX", Descripcion: "6/2 kg (12 kg)", Abreviatura: "2 KG", TipoMedida: "Kilos", PesoKG: 2.0, PesoLb: 4.41, CajasXMaster: 6 },
  { Codigo: "QY", Descripcion: "8/2 kg (16 kg)", Abreviatura: "2 KG", TipoMedida: "Kilos", PesoKG: 2.0, PesoLb: 4.41, CajasXMaster: 8 },
  { Codigo: "RP", Descripcion: "14/3 lb (42 lb)", Abreviatura: "3 LB", TipoMedida: "libras", PesoKG: 1.36, PesoLb: 3.0, CajasXMaster: 14 },
  { Codigo: "RS", Descripcion: "4/2 Kg (8 Kg)", Abreviatura: "2 KG", TipoMedida: "Kilos", PesoKG: 2.0, PesoLb: 4.41, CajasXMaster: 4 },
  { Codigo: "SB", Descripcion: "6/5 lb ( 30 lb )", Abreviatura: "5 LB", TipoMedida: "libras", PesoKG: 2.27, PesoLb: 5.0, CajasXMaster: 6 },
  { Codigo: "SF", Descripcion: "8/5 lb (40 lb)", Abreviatura: "5 LB", TipoMedida: "libras", PesoKG: 2.27, PesoLb: 5.0, CajasXMaster: 8 },
  { Codigo: "SK", Descripcion: "6/1 lb (6 lb)", Abreviatura: "1 LB", TipoMedida: "libras", PesoKG: 0.45, PesoLb: 1.0, CajasXMaster: 6 },
  { Codigo: "TG", Descripcion: "6/2 lb (12 lb)", Abreviatura: "2 LB", TipoMedida: "libras", PesoKG: 0.91, PesoLb: 2.0, CajasXMaster: 6 },
  { Codigo: "US", Descripcion: "8/4 lb (32 lb)", Abreviatura: "4 LB", TipoMedida: "libras", PesoKG: 1.81, PesoLb: 4.0, CajasXMaster: 8 },
];

async function main() {
  for (const cod of PROCESOS_FALTANTES) {
    await p.$executeRawUnsafe(
      `INSERT IGNORE INTO Procesos (Proceso, Descripcion) VALUES (?, ?)`,
      cod, "(pendiente de definir)"
    );
  }
  console.log(`${PROCESOS_FALTANTES.length} procesos placeholder insertados (revisar descripción real en Catálogos → Procesos).`);

  await p.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS Clase (
      Clase       VARCHAR(10)   NOT NULL PRIMARY KEY,
      Familia     VARCHAR(5)    NOT NULL,
      Proceso     INT           NOT NULL,
      Descripcion VARCHAR(150)  NOT NULL,
      TipoClase   VARCHAR(50)   NOT NULL DEFAULT 'PRODUCTO FINAL',
      Activo      TINYINT(1)    NOT NULL DEFAULT 1,
      CONSTRAINT fk_clase_familia FOREIGN KEY (Familia) REFERENCES Familia(Codigo),
      CONSTRAINT fk_clase_proceso FOREIGN KEY (Proceso) REFERENCES Procesos(Proceso)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  `);
  console.log("Tabla Clase creada.");

  await p.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS Presentacion (
      Codigo       VARCHAR(5)    NOT NULL PRIMARY KEY,
      Descripcion  VARCHAR(100)  NOT NULL,
      Abreviatura  VARCHAR(20)   NOT NULL,
      TipoMedida   VARCHAR(20)   NOT NULL,
      PesoKG       DECIMAL(8,3)  NOT NULL,
      PesoLb       DECIMAL(8,3)  NOT NULL,
      CajasXMaster INT           NOT NULL,
      Activo       TINYINT(1)    NOT NULL DEFAULT 1
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  `);
  console.log("Tabla Presentacion creada.");

  for (const c of CLASES) {
    await p.$executeRawUnsafe(
      `INSERT IGNORE INTO Clase (Clase, Familia, Proceso, Descripcion, TipoClase) VALUES (?, ?, ?, ?, ?)`,
      c.Clase, c.Familia, c.Proceso, c.Descripcion, c.TipoClase
    );
  }
  console.log(`${CLASES.length} clases insertadas (INSERT IGNORE).`);

  for (const pr of PRESENTACIONES) {
    await p.$executeRawUnsafe(
      `INSERT IGNORE INTO Presentacion (Codigo, Descripcion, Abreviatura, TipoMedida, PesoKG, PesoLb, CajasXMaster) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      pr.Codigo, pr.Descripcion, pr.Abreviatura, pr.TipoMedida, pr.PesoKG, pr.PesoLb, pr.CajasXMaster
    );
  }
  console.log(`${PRESENTACIONES.length} presentaciones insertadas (INSERT IGNORE).`);

  await p.$disconnect();
}

main().catch(e => { console.error("ERROR:", e.message); process.exit(1); });
